class_name CardTierCatalog
## Complexity tier for every Pokémon card's attack/ability effects.
##
## Tiers:
##   0 — Pure base damage; no effect text; no EffectRegistry handler needed.
##       The existing ActionAttack system handles these completely.
##
##   1 — One simple, self-contained effect:
##         · Coin flip gating bonus damage or a status condition
##         · Unconditional status condition (Asleep, Paralyzed, Poisoned, …)
##         · Optional self-energy discard for a bonus
##         · Simple "N × own energy" or "N × damage counters on target" scaling
##         · Prevent-retreat lock
##         · Small self-heal / remove damage counters
##         · Attach energy from discard to self
##
##   2 — Moderate complexity:
##         · Bench damage (opponent's bench, own bench, all bench)
##         · Deck or discard search
##         · Draw effects
##         · Damage prevention / reduction for a full turn
##         · Energy movement between Pokémon
##         · Forced switch / retreat
##         · Damage scaling across all Pokémon's energy counts
##
##   3 — Complex multi-step or context-sensitive effects:
##         · Opponent hand inspection or disruption
##         · Prize-count conditionals
##         · Multi-turn persistent modifiers
##         · Damage scaling vs. opponent's resource counts
##         · Multi-attack combo chains or unique card-specific rules
##
## Non-Pokémon cards (Trainers, Energy) are not listed here.
## Note: Tiers 1–3 are working approximations; they will be refined as each
## card's EffectRegistry handler is written and tested.

const TIERS: Dictionary = {
	## -------------------------------------------------------------------------
	## Tier 0 — 24 cards — pure base damage, fully implemented
	## -------------------------------------------------------------------------
	"DR_3_crawdaunt":  0,
	"DR_41_shelgon":   0,
	"DR_46_vibrava":   0,
	"DR_49_bagon":     0,
	"DR_51_barboach":  0,
	"DR_53_corphish":  0,
	"DR_61_magnemite": 0,
	"DR_71_pineco":    0,
	"DR_78_trapinch":  0,
	"RS_32_grovyle":   0,
	"RS_36_lairon":    0,
	"RS_46_swellow":   0,
	"RS_50_aron":      0,
	"RS_52_electrike": 0,
	"RS_56_makuhita":  0,
	"RS_63_poochyena": 0,
	"RS_72_taillow":   0,
	"RS_76_treecko":   0,
	"SS_1_armaldo":    0,
	"SS_57_cacnea":    0,
	"SS_65_growlithe": 0,
	"SS_66_lotad":     0,
	"SS_72_pikachu":   0,
	"SS_77_seedot":    0,

	## -------------------------------------------------------------------------
	## Tier 1 — 124 cards — single simple effect
	## -------------------------------------------------------------------------
	"DR_12_torkoal":      1,
	"DR_13_crawdaunt":    1,
	"DR_14_dragonair":    1,
	"DR_15_flygon":       1,
	"DR_19_salamence":    1,
	"DR_23_bagon":        1,
	"DR_24_camerupt":     1,
	"DR_25_combusken":    1,
	"DR_26_dratini":      1,
	"DR_34_houndoom":     1,
	"DR_38_ninjask":      1,
	"DR_39_seadra":       1,
	"DR_43_shuppet":      1,
	"DR_44_snorunt":      1,
	"DR_4_flygon":        1,
	"DR_50_bagon":        1,
	"DR_52_corphish":     1,
	"DR_54_corphish":     1,
	"DR_56_geodude":      1,
	"DR_57_grimer":       1,
	"DR_58_horsea":       1,
	"DR_63_magnemite":    1,
	"DR_64_mareep":       1,
	"DR_65_mudkip":       1,
	"DR_66_nincada":      1,
	"DR_68_nincada":      1,
	"DR_69_numel":        1,
	"DR_6_grumpig":       1,
	"DR_70_numel":        1,
	"DR_74_spoink":       1,
	"DR_75_swablu":       1,
	"DR_77_torchic":      1,
	"DR_79_trapinch":     1,
	"DR_7_minun":         1,
	"DR_80_treecko":      1,
	"DR_89_ampharos_ex":  1,
	"DR_8_plusle":        1,
	"DR_90_dragonite_ex": 1,
	"DR_92_kingdra_ex":   1,
	"DR_93_latias_ex":    1,
	"DR_94_latios_ex":    1,
	"DR_95_magcargo_ex":  1,
	"DR_96_muk_ex":       1,
	"DR_97_rayquaza_ex":  1,
	"DR_99_charmeleon":   1,
	"DR_9_roselia":       1,
	"RS_103_sneasel_ex":  1,
	"RS_11_sceptile":     1,
	"RS_12_slaking":      1,
	"RS_13_swampert":     1,
	"RS_15_blaziken":     1,
	"RS_16_breloom":      1,
	"RS_19_pelipper":     1,
	"RS_1_aggron":        1,
	"RS_22_sharpedo":     1,
	"RS_26_cascoon":      1,
	"RS_29_delcatty":     1,
	"RS_2_beautifly":     1,
	"RS_31_grovyle":      1,
	"RS_33_hariyama":     1,
	"RS_34_kirlia":       1,
	"RS_35_kirlia":       1,
	"RS_40_marshtomp":    1,
	"RS_42_mightyena":    1,
	"RS_43_silcoon":      1,
	"RS_48_wailmer":      1,
	"RS_51_carvanha":     1,
	"RS_53_electrike":    1,
	"RS_58_makuhita":     1,
	"RS_59_mudkip":       1,
	"RS_61_numel":        1,
	"RS_62_phanpy":       1,
	"RS_65_poochyena":    1,
	"RS_66_ralts":        1,
	"RS_67_ralts":        1,
	"RS_69_shroomish":    1,
	"RS_6_dustox":        1,
	"RS_73_torchic":      1,
	"RS_74_torchic":      1,
	"RS_75_treecko":      1,
	"RS_96_chansey_ex":   1,
	"RS_97_electabuzz_ex":1,
	"RS_98_hitmonchan_ex":1,
	"RS_99_lapras_ex":    1,
	"SS_11_seviper":      1,
	"SS_12_shiftry":      1,
	"SS_15_arcanine":     1,
	"SS_16_espeon":       1,
	"SS_19_omastar":      1,
	"SS_20_pichu":        1,
	"SS_24_umbreon":      1,
	"SS_29_arbok":        1,
	"SS_33_breloom":      1,
	"SS_35_electabuzz":   1,
	"SS_38_illumise":     1,
	"SS_40_kirlia":       1,
	"SS_48_nuzleaf":      1,
	"SS_49_nuzleaf":      1,
	"SS_50_pelipper":     1,
	"SS_51_quilava":      1,
	"SS_53_volbeat":      1,
	"SS_56_aron":         1,
	"SS_58_cacnea":       1,
	"SS_59_cyndaquil":    1,
	"SS_5_flareon":       1,
	"SS_64_ekans":        1,
	"SS_67_lotad":        1,
	"SS_68_marill":       1,
	"SS_69_natu":         1,
	"SS_6_jolteon":       1,
	"SS_71_onix":         1,
	"SS_73_psyduck":      1,
	"SS_74_ralts":        1,
	"SS_75_sandshrew":    1,
	"SS_78_shroomish":    1,
	"SS_79_skitty":       1,
	"SS_7_ludicolo":      1,
	"SS_82_trapinch":     1,
	"SS_83_wailmer":      1,
	"SS_84_wingull":      1,
	"SS_94_aerodactyl_ex":1,
	"SS_97_kabutops_ex":  1,
	"SS_98_raichu_ex":    1,
	"SS_99_typhlosion_ex":1,

	## -------------------------------------------------------------------------
	## Tier 2 — 63 cards — moderate complexity
	## -------------------------------------------------------------------------
	"DR_100_charizard":  2,
	"DR_10_salamence":   2,
	"DR_11_shedinja":    2,
	"DR_16_girafarig":   2,
	"DR_17_magneton":    2,
	"DR_18_ninjask":     2,
	"DR_20_shelgon":     2,
	"DR_22_vibrava":     2,
	"DR_28_forretress":  2,
	"DR_30_graveler":    2,
	"DR_33_horsea":      2,
	"DR_36_marshtomp":   2,
	"DR_37_meditite":    2,
	"DR_40_seadra":      2,
	"DR_42_shelgon":     2,
	"DR_48_whiscash":    2,
	"DR_55_geodude":     2,
	"DR_59_houndour":    2,
	"DR_5_golem":        2,
	"DR_60_magikarp":    2,
	"DR_72_slugma":      2,
	"DR_73_spoink":      2,
	"DR_76_taillow":     2,
	"DR_81_wurmple":     2,
	"DR_91_golem_ex":    2,
	"RS_102_scyther_ex": 2,
	"RS_17_donphan":     1,
	"RS_18_nosepass":    2,
	"RS_24_weezing":     2,
	"RS_37_lairon":      2,
	"RS_38_linoone":     2,
	"RS_39_manectric":   2,
	"RS_3_blaziken":     2,
	"RS_44_skitty":      2,
	"RS_49_aron":        2,
	"RS_4_camerupt":     2,
	"RS_57_makuhita":    2,
	"RS_5_delcatty":     2,
	"RS_78_wurmple":     2,
	"RS_9_manectric":    2,
	"SS_100_wailord_ex": 2,
	"SS_13_solrock":     2,
	"SS_23_steelix":     2,
	"SS_27_anorith":     2,
	"SS_30_azumarill":   2,
	"SS_31_azurill":     2,
	"SS_32_baltoy":      2,
	"SS_34_delcatty":    2,
	"SS_36_elekid":      2,
	"SS_37_fearow":      2,
	"SS_39_kabuto":      2,
	"SS_3_cradily":      2,
	"SS_41_lairon":      2,
	"SS_42_lileep":      2,
	"SS_4_dusclops":     2,
	"SS_54_wynaut":      2,
	"SS_60_dunsparce":   2,
	"SS_62_duskull":     2,
	"SS_63_eevee":       2,
	"SS_70_omanyte":     2,
	"SS_81_spearow":     2,
	"SS_8_lunatone":     2,
	"SS_95_aggron_ex":   2,

	## -------------------------------------------------------------------------
	## Tier 3 — 61 cards — complex / unique logic
	## -------------------------------------------------------------------------
	"DR_1_absol":        3,
	"DR_21_skarmory":    3,
	"DR_27_flaaffy":     3,
	"DR_29_graveler":    3,
	"DR_2_altaria":      3,
	"DR_31_grovyle":     3,
	"DR_32_gyarados":    3,
	"DR_35_magneton":    1,
	"DR_45_swellow":     3,
	"DR_47_vibrava":     1,
	"DR_62_magnemite":   3,
	"DR_67_nincada":     1,
	"DR_98_charmander":  1,
	"RS_100_magmar_ex":  3,
	"RS_101_mewtwo_ex":  3,
	"RS_10_mightyena":   3,
	"RS_14_wailord":     1,
	"RS_20_sceptile":    1,
	"RS_21_seaking":     3,
	"RS_23_swampert":    3,
	"RS_25_aron":        1,
	"RS_27_combusken":   1,
	"RS_28_combusken":   1,
	"RS_30_electrike":   3,
	"RS_41_marshtomp":   1,
	"RS_45_slakoth":     3,
	"RS_47_vigoroth":    1,
	"RS_54_koffing":     1,
	"RS_55_goldeen":     3,
	"RS_60_mudkip":      1,
	"RS_64_poochyena":   3,
	"RS_68_ralts":       3,
	"RS_70_skitty":      3,
	"RS_71_skitty":      1,
	"RS_77_wingull":     1,
	"RS_79_zigzagoon":   1,
	"RS_7_gardevoir":    3,
	"RS_8_hariyama":     3,
	"SS_10_sableye":     3,
	"SS_14_zangoose":    3,
	"SS_17_golduck":     3,
	"SS_18_kecleon":     1,
	"SS_21_sandslash":   3,
	"SS_22_shiftry":     3,
	"SS_25_vaporeon":    1,
	"SS_26_wobbuffet":   3,
	"SS_28_anorith":     1,
	"SS_2_cacturne":     3,
	"SS_43_lileep":      3,
	"SS_44_linoone":     2,
	"SS_45_lombre":      1,
	"SS_46_lombre":      3,
	"SS_47_murkrow":     3,
	"SS_52_vigoroth":    3,
	"SS_55_xatu":        3,
	"SS_61_duskull":     3,
	"SS_76_seedot":      1,
	"SS_80_slakoth":     3,
	"SS_85_zigzagoon":   3,
	"SS_96_gardevoir_ex":3,
	"SS_9_mawile":       3,
}


static func tier_of(card_id: String) -> int:
	return TIERS.get(card_id, -1)


static func cards_in_tier(tier: int) -> Array[String]:
	var out: Array[String] = []
	for k: String in TIERS.keys():
		if TIERS[k] == tier:
			out.append(k)
	return out
